### ISSUE TITLE
Panic in debug assertion from general_mat_mul

### ISSUE THREAD

**Issue by frjnn** [rust-ndarray/ndarray#1055]
## Issue

`general_mat_mul` sometimes panics. I hereby copy the message and the code. The error seems to be generated in the matrix multiply crate.

I am on an intel MacBook Pro (2020 model).

### Code

```rust
    #[test]
    fn matrix_multiplication() {
        let m = ndarray::Array::<f32, _>::eye(2);
        let x = ndarray::Array::<f32, _>::ones((2, 3));
        let mut y = ndarray::Array::<f32, _>::zeros((2, 3));

        ndarray::linalg::general_mat_mul(1., &m, &x, 0., &mut y);
    }
```

### Error

```text
running 1 test
thread 'tests::matrix_multiplication' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `0`', /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:293:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:160:17
   3: core::panicking::assert_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:117:5
   4: matrixmultiply::gemm::gemm_packed::{{closure}}
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:293:13
   5: matrixmultiply::threading::RangeChunkParallel<G>::for_each
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/threading.rs:220:25
   6: matrixmultiply::gemm::gemm_packed
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:280:5
   7: matrixmultiply::gemm::gemm_loop::{{closure}}
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:228:21
   8: matrixmultiply::threading::RangeChunkParallel<G>::for_each
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/threading.rs:222:13
   9: matrixmultiply::gemm::gemm_loop
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:212:13
  10: <matrixmultiply::gemm::GemmParameters<T> as matrixmultiply::kernel::GemmSelect<T>>::select
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:121:13
  11: matrixmultiply::sgemm_kernel::detect
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/sgemm_kernel.rs:43:20
  12: matrixmultiply::gemm::sgemm
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.3.0/src/gemm.rs:54:5
  13: ndarray::linalg::impl_linalg::mat_mul_general
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.15.3/src/linalg/impl_linalg.rs:478:13
  14: ndarray::linalg::impl_linalg::general_mat_mul
             at /Users/francesco/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.15.3/src/linalg/impl_linalg.rs:576:9
  15: neuronika::tests::matrix_multiplication
             at ./src/lib.rs:481:9
  16: neuronika::tests::matrix_multiplication::{{closure}}
             at ./src/lib.rs:476:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::matrix_multiplication ... FAILED
```

**Comment by bluss** [comment]
Since it's the same as that bug, then it should already be fixed. Make sure matrixmultiply 0.3.1 is being used.
