### ISSUE TITLE
Scalar Add Op Failure

### ISSUE THREAD

**Issue by jordanmb** [rust-ndarray/ndarray#917]
I assume that the addition here should be commutative but this panics from one side. Not sure how to go about fixing this so I would appreciate any help. Thanks! 

```
thread 'test_ndarray_scalar_add2' panicked at 'ndarray: could not broadcast array from shape: [0] to: []', /home/jordanmb/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.14.0/src/lib.rs:1498:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e2be5f568d1f60365b825530f5b5cb722460591b/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/e2be5f568d1f60365b825530f5b5cb722460591b/library/std/src/panicking.rs:437
   2: ndarray::ArrayBase<S,D>::broadcast_unwrap::broadcast_panic
             at /home/jordanmb/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.14.0/src/lib.rs:1498
   3: ndarray::ArrayBase<S,D>::broadcast_unwrap
             at /home/jordanmb/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.14.0/src/lib.rs:1507
   4: ndarray::impl_methods::<impl ndarray::ArrayBase<S,D>>::zip_mut_with
             at /home/jordanmb/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.14.0/src/impl_methods.rs:1955
   5: ndarray::impl_ops::arithmetic_ops::<impl core::ops::arith::Add<&ndarray::ArrayBase<S2,E>> for ndarray::ArrayBase<S,D>>::add
             at /home/jordanmb/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.14.0/src/impl_ops.rs:99
   6: ndarray::impl_ops::arithmetic_ops::<impl core::ops::arith::Add<ndarray::ArrayBase<S2,E>> for ndarray::ArrayBase<S,D>>::add
             at /home/jordanmb/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.14.0/src/impl_ops.rs:75
```

```
#[test]
pub fn test_ndarray_scalar_add1() {
    let a = Array1::<f64>::zeros((0));
    let b = arr0(0.0);
    let c = a + b; // passes
}
```

```
#[test]
pub fn test_ndarray_scalar_add2() {
    let a = Array1::<f64>::zeros((0));
    let b = arr0(0.0);
    let c = b + a; // fails
}
```

**Comment by bluss** [comment]
It's not commutative due to broadcasting

**Comment by jordanmb** [comment]
Can you elaborate why? This is breaking internally when trying to do some neural network stuff using `autograd`. 

This works just fine in numpy:

```
import numpy as np
a = np.array(0.0)
b = np.array([])
print (a + b).shape
print (b + a).shape
```

**Comment by jturner314** [comment]
Currently, only the right operand is broadcasted in arithmetic operations. There's a PR (#898) in progress to resolve this limitation.

**Comment by bluss** [comment]
It raises the question, the #898 pr "fixes" this, but also adds a new requirement in terms of a trait bound - how does that impact autograd?

**Comment by jordanmb** [comment]
Autograd already let’s you do the operation; it just panics at eval. Ideally invalid tensor shape operations will fail on construction since it's super difficult to source the problem once you're evaluating and have lost your stack trace. I think PR #898 should just work without any changes.
